stages:

- stage: Environment
  jobs:
  - job: Test
    pool: 'Hosted VS2017'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: ganes
    pool: 'Hosted VS2017'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
